# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Console Output Workflow

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  console-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Hello Message
        run: echo "Hello from GitHub Actions!"

      - name: Print Current Date & Time
        run: date

      - name: List Files in Repo
        run: ls -la
